# Generated by Django 4.2.3 on 2023-07-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=11, unique=True, verbose_name='شماره مبایل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254, unique=True, verbose_name='آدرس ایمیل'),
        ),
    ]
