# Generated by Django 4.2.3 on 2023-07-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254, verbose_name='آدرس ایمیل'),
        ),
    ]
