# Generated by Django 4.2.3 on 2023-07-24 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('s', 'هفتم'), ('e', 'هشتم'), ('n', 'نهم')], max_length=1, verbose_name='کلاس')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('lastname', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=255, verbose_name='نام پدر')),
                ('nid', models.CharField(max_length=255, verbose_name='کد ملی')),
                ('creation_certificate', models.CharField(max_length=100, verbose_name='محل ثبت شناسنامه')),
                ('birth_localtion', models.CharField(max_length=100, verbose_name='محل تولد')),
                ('date_of_birth_day', models.CharField(max_length=18, verbose_name='تاریخ تولد')),
                ('the_name_of_privous_school', models.CharField(max_length=300, verbose_name='نام مدرسه قبلی')),
                ('religion', models.CharField(choices=[('eslam', 'اسلام'), ('zartoshti', 'زرتشتی'), ('kalimi', 'کلیمی'), ('masihi', 'مسیحی')], max_length=100, verbose_name='دین')),
                ('religion_of_religion', models.CharField(choices=[('shie', 'شیعه'), ('soni', 'سنی')], default='shie', max_length=100, null=True, verbose_name='مذهب')),
                ('student_parent', models.CharField(choices=[('mother', 'مادر'), ('father', 'پدر'), ('motherANDfather', 'پدرومادر'), ('other', 'سایر')], max_length=100, verbose_name='سرپرست')),
                ('father_first_name', models.CharField(max_length=255, null=True, verbose_name='نام کوچک پدر')),
                ('father_last_name', models.CharField(max_length=255, null=True, verbose_name='نام خانوادگی پدر')),
                ('father_date_of_birth_day', models.CharField(max_length=18, null=True, verbose_name='تاریخ تولد پدر')),
                ('level_of_education_father', models.CharField(choices=[('dont', 'بی سواد'), ('five', 'پنجم ابتدایی'), ('sicle', 'سیکل'), ('diplom', 'دیپلوم'), ('udiplom', 'فوق دیپلوم'), ('lisans', 'لیسانس'), ('ulisans', 'فوق لیسانس'), ('doctor', 'دکترا')], max_length=100, verbose_name='میزان تحصیلات پدر')),
                ('job_father', models.CharField(max_length=255, null=True, verbose_name='شغل پدر')),
                ('telephone_number_work_location_father', models.CharField(max_length=11, null=True, verbose_name='شماره تلفن محل کار پدر')),
                ('work_location_adderss_father', models.CharField(max_length=10000000000000000, null=True, verbose_name='ادرس محل کار پدر')),
                ('father_phone_number', models.CharField(max_length=11, null=True, verbose_name='شماره تلفن پدر')),
                ('father_live', models.BooleanField(verbose_name='ایا پدر زنده است')),
                ('mother_first_name', models.CharField(max_length=255, verbose_name='نام کوچک مادر')),
                ('mother_last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی مادر')),
                ('mother_date_of_birth_day', models.CharField(max_length=18, verbose_name='تاریخ تولد مادر')),
                ('level_of_education_mother', models.CharField(choices=[('dont', 'بی سواد'), ('five', 'پنجم ابتدایی'), ('sicle', 'سیکل'), ('diplom', 'دیپلوم'), ('udiplom', 'فوق دیپلوم'), ('lisans', 'لیسانس'), ('ulisans', 'فوق لیسانس'), ('doctor', 'دکترا')], max_length=100, verbose_name='میزان تحصیلات مادر')),
                ('job_mother', models.CharField(max_length=255, null=True, verbose_name='شغل مادر')),
                ('telephone_number_work_location_mother', models.CharField(max_length=11, verbose_name='شماره تلفن محل کار مادر')),
                ('work_location_adderss_mother', models.CharField(max_length=100000000000000000000, verbose_name='ادرس محل کار مادر')),
                ('mother_phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن مادر')),
                ('mother_live', models.BooleanField(verbose_name='ایا مادر زنده است')),
                ('ghaim_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کوچک سرپرست')),
                ('ghaim_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی سرپرست')),
                ('ghaim_date_of_birth_day', models.CharField(blank=True, max_length=18, null=True, verbose_name='تاریخ تولد سرپرست')),
                ('level_of_education_ghaim', models.CharField(blank=True, choices=[('dont', 'بی سواد'), ('five', 'پنجم ابتدایی'), ('sicle', 'سیکل'), ('diplom', 'دیپلوم'), ('udiplom', 'فوق دیپلوم'), ('lisans', 'لیسانس'), ('ulisans', 'فوق لیسانس'), ('doctor', 'دکترا')], max_length=100, null=True, verbose_name='میزان تحصیلات سرپرست')),
                ('job_ghaim', models.CharField(blank=True, max_length=255, null=True, verbose_name='شغل سرپرست')),
                ('telephone_number_work_location_ghaim', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن محل کار سرپرست')),
                ('work_location_adderss_ghaim', models.CharField(blank=True, max_length=100000000000000000000, null=True, verbose_name='ادرس محل کار سرپرست')),
                ('ghaim_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن سرپرست')),
                ('street', models.CharField(max_length=100000000, verbose_name='خیابان')),
                ('alley', models.CharField(max_length=100000000, verbose_name='کوی')),
                ('alley_alley', models.CharField(max_length=100000000, verbose_name='کوچه')),
                ('plaque', models.CharField(max_length=5, verbose_name='پلاک')),
                ('floor', models.CharField(max_length=3, verbose_name='طبقه')),
                ('postal_code', models.CharField(max_length=22, verbose_name='کد پستی')),
                ('telephone_number', models.CharField(max_length=11, verbose_name='تلفن')),
                ('number_of_shad', models.CharField(max_length=11, verbose_name='شماره متصل به شبکه شاد')),
                ('emergensy_phone', models.CharField(max_length=11, verbose_name='شماره اضتراری')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
