# Generated by Django 4.2.3 on 2023-07-25 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve', to=settings.AUTH_USER_MODEL),
        ),
    ]
