# Generated by Django 4.2.3 on 2024-08-03 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desine', '0003_alter_image_options_remove_image_date_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'عکس', 'verbose_name_plural': 'عکس ها'},
        ),
    ]
