# Generated by Django 4.2.3 on 2023-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='englishTitle',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
