# Generated by Django 4.2.3 on 2023-07-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_options_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='englishTitle',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان انگلیسی مقاله'),
            preserve_default=False,
        ),
    ]
