# Generated by Django 4.2.3 on 2023-07-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_englishtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='englishName',
            field=models.CharField(default=1, max_length=255, verbose_name='عنوان انگلیسی دسته\u200cبندی'),
            preserve_default=False,
        ),
    ]
