# Generated by Django 4.2.3 on 2023-07-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_category_options_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='englishTitle',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان انگلیسی مقاله'),
        ),
    ]
